"""empty message

Revision ID: 086df854d6cf
Revises: 1575ca6b5274
Create Date: 2022-05-24 15:24:21.425849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086df854d6cf'
down_revision = '1575ca6b5274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_category', 'created_date')
    # ### end Alembic commands ###
